language: ruby
sudo: false
rvm:
  - "ruby-2.2.2"
  - "ruby-2.3.1"
  - "ruby-2.4.0"
  - "ruby-2.5.0"
  - "jruby-9.0.0.0"

matrix:
  allow_failures:
    - rvm: rbx-2
cache: bundler
before_install:
  - gem update bundler
script:
  - bundle exec rspec spec
  - bundle exec cucumber
